<?php
// $Id$

/**
 * @file
 * Calendar Customizations Module
 * This module adds customizations to the Calendar contrib module
 */

/**
 * Implements hook_help().
 */
function calendar_plus_help($path, $arg) {
  if ($path == 'admin/help#calendar_plus') {
    return t(
      'This module is a companion to the Calendar module. Most of the calendar functionality is still ' 
      . 'handled by the Calendar module. This companion over-rides the out-put and converts the calendar ' 
      . ' to responsive HTML/CSS. It does this by swapping out the table-based output for unordered list '
      . ' output instead, where appropriate'
    );
  }
}

/**
 * Implementation of hook_views_plugins
 */
function calendar_plus_views_plugins() {

  $views_path  = drupal_get_path('module', 'views');
  $module_path = drupal_get_path('module', 'calendar_plus');
  $theme_path  = $module_path;
  module_load_include('inc', 'calendar_plus', 'theme/theme');

  // Limit these plugins to base tables that represent entities.
  $base = array_keys(date_views_base_tables());

  $data = array(
    'module' => 'calendar', // This just tells our themes are elsewhere.
    'style' => array(
      'calendar_style' => array(
        'title' => t('Calendar'),
        'help' => t('Present view results as a Calendar.'),
        'handler' => 'calendar_plus_plugin_style',
        'path' => "$module_path/includes",
        'theme' => 'calendar_style',
        'theme file' => 'theme.inc',
        'theme path' => "$theme_path/theme",
        'additional themes' => array(
          'calendar_mini' => 'style',
          'calendar_day' => 'style',
          'calendar_week' => 'style',
          'calendar_month' => 'style',
          'calendar_year' => 'style',
          'calendar_day_overlap' => 'style',
          'calendar_week_overlap' => 'style',
        ),
        'uses fields' => TRUE,
        'uses grouping' => FALSE,
        'uses row plugin' => TRUE,
        'uses options' => TRUE,
        'type' => 'normal',
        'even empty' => TRUE,
        'base' => $base,
      ),
    ),
    'row' => array(
      'calendar_node' => array(
        'title' => t('Calendar Items (DEPRECATED, switch to Calendar Entities)'),
        'help' => t('Displays each selected node as a Calendar item.'),
        'handler' => 'calendar_plugin_row_node',
        'path' => "$module_path/includes",
        'base' => array('node'), // only works with 'node' as base.
        'uses options' => TRUE,
        'uses fields' => TRUE,
        'type' => 'normal',
        'no ui' => TRUE,
      ),
      'calendar_entity' => array(
        'title' => t('Calendar Entities'),
        'help' => t('Displays each selected entity as a Calendar item.'),
        'handler' => 'calendar_plus_plugin_row',
        'theme' => 'views_view_fields',
        'path' => "$module_path/includes",
        'base' => $base,
        'uses options' => TRUE,
        'uses fields' => TRUE,
        'type' => 'normal',
      ),
    ),
  );
  return $data;
}

/**
 * Implements hook_theme().
 */
function calendar_plus_theme() {
  $module_path = drupal_get_path('module', 'calendar_plus');

  $base = array(
    'file' => 'theme.inc',
    'path' => "$module_path/theme",
  );
  return array(
    'calendar_item' => $base + array(
      'template' => 'calendar-item',
      'variables' => array('view' => NULL, 'rendered_fields' => NULL, 'item' => NULL),
    ),
    'calendar_datebox' => $base + array(
      'template' => 'calendar-datebox',
      'variables' => array(
        'date' => NULL, 'view' => NULL, 'items' => NULL, 'selected' => NULL),
    ),
    'calendar_plus_empty_day' => $base + array(
      'variables' => array('curday' => NULL, 'view' => NULL),
    ),
    'calendar_stripe_legend' => $base + array(
      'variables' => array('view' => NULL),
    ),
    'calendar_stripe_stripe' => $base + array(
      'variables' => array('node' => NULL),
    ),
    'calendar_time_row_heading' => $base + array(
      'variables' => array('start_time' => NULL, 'next_start_time' => NULL, 'curday_date' => NULL),
    ),
    'calendar_month_col' => $base + array(
      'template' => 'calendar-month-col',
      'variables' => array('item' => NULL),
    ),
    'calendar_month_row' => $base + array(
      'template' => 'calendar-month-row',
      'variables' => array('inner' => NULL, 'class' => NULL, 'iehint' => NULL),
    ),
    'calendar_month_multiple_entity' => $base + array(
      'template' => 'calendar-month-multiple-entity',
      'variables' => array('
         curday' => NULL, 'count' => NULL, 'view' => NULL, 'ids' => NULL),
    ),
  );
}

